version: '2'
services:
  db:
    image: mvertes/alpine-mongo
    ports:
      - "127.0.0.1:27017:27017"

  nginx-php7.0:
    build:
      context: ./docker
      dockerfile: ./Dockerfile-php7.0
    ports:
      - "127.0.0.1:1241:8100"
    links:
      - db
    volumes:
      - ./:/usr/share/nginx/html
    command: ["bash", "/usr/share/nginx/html/docker/launch-f43me.sh"]

  # nginx-php7.1:
  #   build:
  #     context: ./docker
  #     dockerfile: ./Dockerfile-php7.1
  #   ports:
  #     - "8100:8100"
  #   links:
  #     - db
  #   volumes:
  #     - ./:/usr/share/nginx/html
  #   command: ["bash", "/usr/share/nginx/html/docker/launch-f43me.sh"]
